INSERT INTO ROLES (ROLE) values('ADMIN');
INSERT INTO ROLES (ROLE) values('CLIENT');
INSERT INTO ROLES (ROLE) values('MANTEINER');


INSERT INTO CLIENTS (CLI_USERNAME, CLI_NAME, CLI_LASTNAME, CLI_PASSWORD) VALUES ('franco_magris', 'Franco', 'Magris', '$2a$10$XRZ1W2Wyh02iKEizsZetVu7tvX4yDGHn30KX2ybniQar5bKBH2daW');
INSERT INTO CLIENTS (CLI_USERNAME, CLI_NAME, CLI_LASTNAME, CLI_PASSWORD) VALUES ('angeles_rusconi', 'Angeles', 'Rusconi', '$2a$10$cbv.ifuDUCvR/SbSd3PyauaTHOoH3f3NlnIARlpTV7W1XnPeDDJVG');


INSERT INTO CLIENT_ROLES (CLI_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO CLIENT_ROLES (CLI_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO CLIENT_ROLES (CLI_ID, ROLE_ID) VALUES (2, 2);